version: '3.4'

services:
  customer.register.api:
    image: customerregisterapi
    build:
      context: .
      dockerfile: Customer.Register.Api/Dockerfile
    extra_hosts:
      - "customer.sql.data:10.0.75.1"